version: "3.9"

services:
  backend:
    build:
      context: ./app
    container_name: aqz_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
